

register:
  path: /register
  controller: App\Controller\UserController::createUser

login:
  path: /login
  controller: App\Controller\UserController::login

groups:
  path: /groups/new
  controller: App\Controller\GroupController::createGroup

group:
  path: /groups/getGroup
  controller: App\Controller\GroupController::getGroup

groupss:
  path: /groups/
  controller: App\Controller\GroupController::getGroups

help:
  path: /groups/id/help/
  controller: App\Controller\HelpController::createHelp

helpGroup:
  path: /groups/id/help/id
  controller: App\Controller\HelpController::getHelps