
register_app2:
  path: /login2
  controller: App\Controller\UserController::createUser
register_app:
  path: /register2
  controller: App\Controller\UserController::createUser

groups:
  path: /groups/new
  controller: App\Controller\GroupController::createGroup

group:
  path: /groups/getGroup
  controller: App\Controller\GroupController::getGroup

userGroups:
  path: /groups/userGroups
  controller: App\Controller\GroupToUserController::getUserGroup

groupss:
  path: /groups/
  controller: App\Controller\GroupController::getGroups

help:
  path: /help
  controller: App\Controller\HelpController::createHelp
removeHelp:
  path: /removeHelp
  controller: App\Controller\HelpController::removeHelp


authentication_token:
  path: /authentication_token
  methods: ['POST']

api_login_check:
  path: /api/login_check