

register:
  path: /register
  controller: App\Controller\UserController::createUser

login:
  path: /login
  controller: App\Controller\UserController::login

groups:
  path: /groups/new
  controller: App\Controller\GroupController::createGroup
